apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: reverseproxy
  name: publicreverseproxy
  namespace: udagram
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reverseproxy
  type: LoadBalancer
status:
  loadBalancer: {}
