apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: udagram-frontend
  name: publicfrontend
  namespace: udagram
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: udagram-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
