apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: udagram-api-user
  name: udagram-api-user
  namespace: udagram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: udagram-api-user
    spec:
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
      containers:
      - image: lim0nes/udagram-api-user:latest
        name: udagram-api-user
        resources: {}
        volumeMounts:
          - name: aws-secret
            mountPath: "root/.aws"
            readOnly: true
        envFrom:
          - configMapRef:
              name: udagram-cm
          - secretRef:
              name: udagram-secret
status: {}
