apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: udagram-frontend
  name: udagram-frontend
  namespace: udagram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: udagram-frontend
    spec:
      containers:
      - image: lim0nes/udagram-frontend:latest
        name: udagram-frontend
        resources: {}
status: {}
