apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: udagram-api-feed
  name: udagram-api-feed
  namespace: udagram
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-api-feed
status:
  loadBalancer: {}
